name: Protoc Build

on:
  workflow_call:

jobs:
  build:
    name: Protoc Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Protoc
        run: |
          sudo apt install -y protobuf-compiler

      - name: Compile and Test
        run: sh run_protocol_compilers.sh
  build-scala:
    name: ScalaPB Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup SBT
        run: |
          mkdir -p $HOME/bin/sbt
          set -eux && curl --fail --silent --location --retry 3 https://github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.tgz | gunzip | tar x -C $HOME/bin/sbt
          echo "$HOME/bin/sbt" >> $GITHUB_PATH

      - name: Compile and Test
        run: sbt publishLocal
        working-directory: build/scala
        
  build-dart:
    name: Dart Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Setup Dart protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          dart pub global activate protoc_plugin

      - name: Compile and Test
        run: |
          ./compile_protos.sh
          dart pub get
          dart run tool/generate_export_files.dart
          dart analyze
          dart test
        working-directory: build/dart
      - name: Upload Dart Compiled Lib
        uses: actions/upload-artifact@v4
        with:
          name: dart-compiled-lib
          path: "build/dart/lib"
          
  build-ts:
    name: TypeScript Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'build/ts/package-lock.json'

      - name: Setup Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build for TypeScript
        run: |
          ./build.sh
        working-directory: build/ts

      - name: Lint and Test
        run: |
          npm run lint
          npm test
        working-directory: build/ts

      - name: Upload TypeScript Compiled Lib
        uses: actions/upload-artifact@v4
        with:
          name: ts-compiled-lib
          path: |
            build/ts/dist/**
            build/ts/proto/**
            build/ts/src/**
            build/ts/package.json
            build/ts/package-lock.json
            build/ts/tsconfig.json
            build/ts/*.config.*
            build/ts/README.md
            !build/ts/**/node_modules/**