name: deploy
on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  build:
    name: Protoc Test Build and Compile
    uses: ./.github/workflows/_protoc_build.yml
  publish-scala:
    name: Publish Scala
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy Scala (release only)
        run: sbt ci-release
        working-directory: ./build/scala
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish-dart:
    name: Publish Scala
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dart-lang/setup-dart@v1
      - uses: actions/download-artifact@v4
        with:
          name: dart-compiled-lib
          path: build/dart
      - run: dart pub get
        working-directory: ./build/dart
      - name: Deploy Dart (release only)
        run: dart pub publish --force
        working-directory: ./build/dart
